### ISSUE TITLE
Integrate uboot for the RasberryPi boards

### ISSUE THREAD

**Issue by imrehg** [balena-os/resin-raspberrypi#148]
We want to migrate to choosing the rootfs based on a counter. As we can't do this in the proprietary bootloader, we will need to integrate uboot first.

**Comment by floion** [comment]
@imrehg this needs a description. I do not understand what this is for

**Comment by imrehg** [comment]
@floion this is a PR made as per @agherzan's request late night on Friday, he'll add more.

**Comment by agherzan** [comment]
@floion added.

**Comment by floion** [comment]
u-boot is now used in the bootchain, closing this issue
