### ISSUE TITLE
Update firmware to support rPI 3B+ PoE hat (+ fan) 

### ISSUE THREAD

**Issue by christopherhex** [balena-os/resin-raspberrypi#240]
New Raspberry [Pi PoE hat](
https://www.raspberrypi.org/products/poe-hat/) has a fan that can be controlled through the firmware. This requires an updated linux-firmware.  

Also see this commit:  [raspberrypi/firmware - 953a33](https://github.com/raspberrypi/firmware/commit/953a33962f0e3a33f7627248f47b8378cb40e6e4)

**Comment by floion** [comment]
Thanks for the input. Andrei already created https://github.com/agherzan/meta-raspberrypi/pull/312 to handle this in the BSP. Let's see if this gets backported to Sumo

**Comment by agherzan** [comment]
Pushed a PR which adds this support in sumo: https://github.com/agherzan/meta-raspberrypi/pull/314

**Comment by christopherhex** [comment]
Hi @agherzan, thanks! 
Any ETA when it will be included in an upcoming release of this repo?

**Comment by agherzan** [comment]
Keep an eye on the releases for the RaspberryPi. I'd probably say 2 weeks.

**Comment by floion** [comment]
Implemented in https://github.com/resin-os/resin-raspberrypi/pull/243
