### ISSUE TITLE
Test defining init_uart_clock in config.txt and unblacklist it if it's safe

### ISSUE THREAD

**Issue by pimterry** [balena-os/resin-raspberrypi#248]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_e5cz)

**Comment by floion** [comment]
@CameronDiver I guess this is something to be handled by the supervisor, right?

**Comment by majorz** [comment]
PR is merged now: https://github.com/resin-io/resin-supervisor/pull/752

**Comment by thomasgubler** [comment]
At which resin version is this available? (FYI @RomanBapst )

**Comment by floion** [comment]
@thomasgubler it should be available in 2.26.0+rev1 which is due today or tomorrow
