### ISSUE TITLE
 Remove references to `bcm2708_wdog` kernel module where wdog is compiled into the kernel

### ISSUE THREAD

**Issue by xginn8** [balena-os/resin-raspberrypi#256]
(moving from https://github.com/resin-os/meta-resin/issues/1246)
Since the watchdog functionality on the Pi3 is baked into the kernel and no longer loaded as a module, we should remove references to the `bcm2708_wdog` kernel module to avoid confusion.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ejj7)

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/resin-raspberrypi/pull/267
