### ISSUE TITLE
Don't stop the boot process if uboot receives a vertical tab or CTRL+C

### ISSUE THREAD

**Issue by LucianBuzzo** [balena-os/resin-raspberrypi#269]
Currently, uboot will stop the boot process if either a vertical tab or CTRL+C gets sent to it over a serial cable when starting.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_faqz)

**Comment by floion** [comment]
@shaunmulligan do you agree we disable any option to stop at the uboot shell?

**Comment by shaunmulligan** [comment]
@floion yeah I think that is wise

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/resin-raspberrypi/pull/270

**Comment by shaunmulligan** [comment]
fixed and released in v2.27.0+rev1
